spring:
  datasource:
    url: jdbc:postgresql://:5432/testdb
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: n1tjrgnsdev@gmail.com
    password: kytbfwvyymkzohcw
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true



